[package]
name = "dither"
version = "0.1.0"
authors = ["Matthew Blode <m@blode.co>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bluenoise = "0.1.2"
image = "0.23.12"
rand = "0.3"
